package com.kernelloader.driver

import android.content.Context
import com.topjohnwu.superuser.Shell
import java.io.File

object DriverAutoload {

    private const val STAGE_PRIMARY = "/data/adb/kloder"
    private const val STAGE_FALLBACK = "/data/local/tmp/kloder"

    private const val SCRIPT_PRIMARY = "/data/adb/service.d/90-kloder.sh"
    private const val SCRIPT_FALLBACK = "/data/local/tmp/kloder-autoload.sh"

    private const val PREFS = "kloder_autoload"

    private fun prefs(ctx: Context) =
        ctx.getSharedPreferences(PREFS, Context.MODE_PRIVATE)

    var enabled: Boolean
        get() = _enabled
        private set(v) { _enabled = v }

    private var _enabled = false

    var stagedKo: String = ""
        private set

    var moduleName: String = ""
        private set

    var variant: String = ""
        private set

    var devNode: String = "wanbai"
        private set

    var lastBootLog: String = ""
        private set

    fun state(ctx: Context) {
        prefs(ctx).let { p ->
            _enabled = p.getBoolean("enabled", false)
            stagedKo = p.getString("ko", "") ?: ""
            moduleName = p.getString("module", "") ?: ""
            variant = p.getString("variant", "") ?: ""
            devNode = p.getString("node", "wanbai") ?: "wanbai"
        }
    }

    private fun save(ctx: Context) {
        prefs(ctx).edit()
            .putBoolean("enabled", _enabled)
            .putString("ko", stagedKo)
            .putString("module", moduleName)
            .putString("variant", variant)
            .putString("node", devNode)
            .apply()
    }

    private fun hasMagisk(): Boolean =
        try { Shell.cmd("ls -d /data/adb 2>/dev/null").exec().isSuccess } catch (e: Exception) { false }

    fun stageDir(): String = if (hasMagisk()) STAGE_PRIMARY else STAGE_FALLBACK

    fun scriptPath(): String = if (hasMagisk()) SCRIPT_PRIMARY else SCRIPT_FALLBACK

    fun hasBootRunner(): Boolean = try {
        Shell.cmd(
            "ls -d /data/adb/service.d 2>/dev/null || " +
                    "ls -d /data/adb/modules 2>/dev/null || " +
                    "ls /data/adb/magisk 2>/dev/null"
        ).exec().isSuccess
    } catch (e: Exception) {
        false
    }

    private fun buildScript(): String {
        
        val dir = stageDir()
        val ko = stagedKo
        val mod = moduleName
        val nodeName = devNode.trim().ifEmpty { "wanbai" }
        val node = "/dev/$nodeName"
        val fam = variant.uppercase()
        val shell = """
#!/system/bin/sh
# ---------------------------------------------------------------
# Kernel Loader - load the memory driver at boot.
# Generated by the Kernel Loader app. Safe to delete.
#
# Module     : @MODNAME@
# ABI family : @FAMILY@
# Device node: @NODE@
# ---------------------------------------------------------------
DIR="@DIR@"
KO="@KO@"
MOD="@MODNAME@"
NODE="@NODE@"
LOG="@DIR@/boot.log"

mkdir -p "@DIR@" 2>/dev/null
say() { echo "@(date '+%H:%M:%S') @*" >> "@LOG@"; }

say "boot auto-load starting (module=@MODNAME@)"

# 1. wait for /data to carry the staged .ko (max 60s)
i=0
while [ ! -f "@KO@" ]; do
    i=@((i+1))
    if [ @i -gt 60 ]; then
        say "ABORT: @KO@ never appeared"
        exit 1
    fi
    sleep 1
done
say "found staged driver"

# 2. let init/vold finish so the driver does not compete with boot
#    (bounded at 90s; a missing getprop must not hang us forever)
i=0
while [ @i -lt 90 ]; do
    getprop sys.boot_completed 2>/dev/null | grep -q '1' && break
    i=@((i+1))
    sleep 1
done
say "boot stage released"

# 3. permissive SELinux before anything else: the game-mod client is a
#    separate uid and cannot open the node while SELinux enforces, and every
#    exit path below (including the already-loaded skip) needs this.
ENF=@(getenforce 2>/dev/null)
if [ "@ENF@" = "Enforcing" ]; then
    if setenforce 0 2>/dev/null; then
        say "SELinux -> Permissive"
    else
        say "WARN: setenforce 0 denied - game apps may not reach the node"
    fi
else
    say "SELinux already @ENF@"
fi

# 4. already loaded? no-op. A module lives in kernel memory until reboot, and
#    a manual load may have run before, so never insmod twice.
if grep -q "^@MODNAME@ " /proc/modules 2>/dev/null; then
    say "SKIP: @MODNAME@ is already loaded"
    chmod 666 "@NODE@" 2>/dev/null
    say "done (node perms refreshed)"
    exit 0
fi

# 5. load it - devname pins the node name the client opens; without it the
#    driver registers its built-in default and @NODE@ never appears
chmod 644 "@KO@" 2>/dev/null
if insmod "@KO@" devname="@NODENAME@" >> "@LOG@" 2>&1; then
    say "OK: insmod succeeded (devname=@NODENAME@)"
elif insmod "@KO@" >> "@LOG@" 2>&1; then
    say "OK: insmod succeeded (legacy build, no devname)"
else
    say "FAIL: insmod failed (details in @LOG@.why)"
    tail -n 5 "@LOG@" > "@LOG@.why" 2>/dev/null
fi

# 6. the client opens the node as any uid -> world R/W
sleep 1
if [ -e "@NODE@" ]; then
    chmod 666 "@NODE@" 2>/dev/null
    say "OK: @NODE@ present, perms 666"
else
    say "WARN: @NODE@ missing - is the driver really loaded?"
fi
say "boot auto-load finished"
""".trimIndent() + "\n"
        
        val out = shell
            .replace("@MODNAME@", mod)
            .replace("@FAMILY@", fam)
            .replace("@NODENAME@", nodeName)
            .replace("@NODE@", node)
            .replace("@KO@", ko)
            .replace("@DIR@", dir)
            .replace("@LOG@", "$dir/boot.log")

            .replace("@ENF@", "\$ENF")
            .replace("@", "$")
        
        if (out.contains('@')) {
            val bad = Regex("@[A-Za-z0-9_]*").findAll(out).map { it.value }.distinct()
            throw IllegalStateException("boot script template has unknown placeholders: ${bad.joinToString()}")
        }
        return out
    }

    fun enable(ctx: Context, koFile: File, modName: String, family: String, node: String, log: (String, String) -> Unit): Boolean {
        if (modName.isBlank() || modName == "Module") {
            log("AUTOLOAD: refusing - the loaded module name is unknown", "ERR")
            return false
        }
        val dir = stageDir()
        val dst = "$dir/driver.ko"
        val res = try {
            Shell.cmd(
                "mkdir -p $dir",
                "cp '${koFile.absolutePath}' $dst",
                "chmod 644 $dst",
                "sync"
            ).exec()
        } catch (e: Exception) {
            log("AUTOLOAD: staging failed: ${e.message}", "ERR")
            return false
        }
        if (!res.isSuccess) {
            log("AUTOLOAD: could not stage the .ko into $dir", "ERR")
            res.err.forEach { if (it.isNotBlank()) log("AUTOLOAD: $it", "ERR") }
            return false
        }

        moduleName = modName.trim()
        variant = family.trim()
        devNode = node.trim().ifEmpty { "wanbai" }
        stagedKo = dst

        val script = try {
            buildScript()
        } catch (e: Exception) {
            log("AUTOLOAD: refusing to install a boot script we could not render", "ERR")
            log("AUTOLOAD: ${e.message}", "ERR")
            _enabled = false
            save(ctx)
            return false
        }
        val scriptPath = scriptPath()
        val w = try {
            
            Shell.cmd("mkdir -p \$(dirname $scriptPath)").exec()
            File(ctx.cacheDir, "kloder-boot.sh").apply {
                writeText(script)
            }.let { tmp ->
                Shell.cmd("cp '${tmp.absolutePath}' $scriptPath", "chmod 755 $scriptPath", "sync").exec()
            }
        } catch (e: Exception) {
            log("AUTOLOAD: could not write $scriptPath: ${e.message}", "ERR")
            return false
        }
        if (!w.isSuccess) {
            w.err.forEach { if (it.isNotBlank()) log("AUTOLOAD: $it", "ERR") }
            log("AUTOLOAD: boot script NOT installed", "ERR")
            return false
        }

        _enabled = true
        save(ctx)
        log("AUTOLOAD: boot script installed -> $scriptPath", "OK")
        log("AUTOLOAD: will insmod '$moduleName' (${variant.uppercase()}) at every boot", "OK")
        log("AUTOLOAD: node $devNode, log $dir/boot.log", "INFO")
        return true
    }

    fun disable(ctx: Context, log: (String, String) -> Unit) {
        val p = scriptPath()
        val dir = stageDir()
        val res = try {
            Shell.cmd("rm -f $p", "$dir/boot.log $dir/boot.log.why 2>/dev/null", "sync").exec()
        } catch (e: Exception) {
            log("AUTOLOAD: remove failed: ${e.message}", "ERR")
            return
        }
        _enabled = false
        save(ctx)
        log(
            if (res.isSuccess) "AUTOLOAD: boot script removed -> driver will NOT auto-load"
            else "AUTOLOAD: could not remove $p (exit ${res.code})",
            if (res.isSuccess) "OK" else "ERR"
        )
    }

    fun statusLine(ctx: Context): String {
        state(ctx)
        if (!_enabled) return "Auto-load at boot: OFF"
        val m = moduleName.ifEmpty { "?" }
        return "Auto-load at boot: ON  ($m at every boot)"
    }

    fun readBootLog(): String = try {
        Shell.cmd("cat ${stageDir()}/boot.log 2>/dev/null | tail -n 20").exec().out
            .filter { it.isNotBlank() }.joinToString("\n")
    } catch (e: Exception) {
        ""
    }
}
